[mysqld]
datadir=D:/react-project-builder-mainmanishasree/react-project-builder-mainmanisha(1)1818/react-project-builder-mainmanisha(1)/react-project-builder-main (1)/react-project-builder-main/.local-data/mariadb
[client]
plugin-dir=C:\Program Files\MariaDB 13.0/lib/plugin
